connector:
    name: Akeneo Mass Edit Connector
    jobs:
        update_product:
            title: update_product
            type:  mass_edit
            steps:
                perform:
                    title: update_product
                    class: "%pim_base_connector.step.mass_edit_update_product.class%"
                    services:
                        handler: pim_enrich.mass_edit_handler.update_product

#        update_family:
#            title: update_family
#            type:  mass_edit
#            steps:
#                perform:
#                    title: update_family
#                    class: "%pim_base_connector.step.mass_edit_update_family.class%"
#                    services:
#                        handler: pim_enrich.mass_edit_handler.update_product
